# Funding for this project.
#
# Everything here is MIT-licensed and stays free regardless. Sponsorship goes
# towards the hardware and the electricity of the homelab that hosts the
# public services, and towards the maintenance that never shows up in a
# release note.
github: jmrplens
