# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: portainer-mcp-enhanced

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - id: portainer-mcp
    main: ./cmd/portainer-mcp-enhanced
    binary: portainer-mcp-enhanced
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.ShortCommit}}
      - -X main.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
      - tools.yaml

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\(.+\))?\!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\(.+\))?\!?:.+$'
      order: 1
    - title: "🔒 Security"
      regexp: '^.*?sec(\(.+\))?\!?:.+$'
      order: 2
    - title: "📦 Other"
      order: 999

release:
  github:
    owner: jmrplens
    name: portainer-mcp-enhanced
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
  header: |
    ## Portainer MCP Enhanced {{.Tag}}

    ### Installation

    **Go install:**
    ```bash
    go install github.com/jmrplens/portainer-mcp-enhanced/cmd/portainer-mcp-enhanced@{{.Tag}}
    ```

    **Docker:**
    ```bash
    docker pull ghcr.io/jmrplens/portainer-mcp-enhanced:{{.Tag}}
    ```

    **Manual download:** See assets below for your platform.
  footer: |
    **Full Changelog**: https://github.com/jmrplens/portainer-mcp-enhanced/compare/{{.PreviousTag}}...{{.Tag}}

# Homebrew tap — disabled (no personal tap available yet)
# brews:
#   - name: portainer-mcp-enhanced
#     repository:
#       owner: jmrplens
#       name: homebrew-tap
#       token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
#     directory: Formula
#     homepage: "https://github.com/jmrplens/portainer-mcp-enhanced"
#     description: "Enhanced MCP server for AI-powered Portainer container management"
#     license: "Zlib"
#     install: |
#       bin.install "portainer-mcp"
#     skip_upload: auto

# Docker images via GHCR (multi-arch manifest, no per-arch tags)
dockers_v2:
  - images:
      - "ghcr.io/jmrplens/portainer-mcp-enhanced"
    tags:
      - "v{{ .Version }}"
      - "{{ if not .Prerelease }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - tools.yaml
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "Enhanced MCP server for AI-powered Portainer container management"
      "org.opencontainers.image.source": "https://github.com/jmrplens/portainer-mcp-enhanced"
      "org.opencontainers.image.license": "Zlib"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.created": "{{ .Date }}"
