// Command gen_applicability derives per-operation version ranges from every
// published Portainer specification and writes them as Go source.
//
// Presence was measured as contiguous in semver order for 100 % of CE
// operations and 98 % of EE, with the three exceptions explained in the design
// specification. Any new gap this command finds is reported rather than
// smoothed over, because a gap means an operation was genuinely withdrawn and
// reintroduced.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type operation struct {
	Method string
	Path   string
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "gen_applicability: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	fs := flag.NewFlagSet("gen_applicability", flag.ContinueOnError)
	historyDir := fs.String("history", "api/specs/history", "directory of <edition>-<version>.json specs")
	out := fs.String("out", "internal/apiversion/applicability_gen.go", "file to write")
	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("parse flags: %w", err)
	}

	entries, err := os.ReadDir(*historyDir)
	if err != nil {
		return fmt.Errorf("read %s: %w", *historyDir, err)
	}

	// edition -> version -> set of operations
	presence := map[string]map[string]map[operation]bool{}
	for _, entry := range entries {
		name := entry.Name()
		if !strings.HasSuffix(name, ".json") || strings.Contains(name, "provenance") {
			continue
		}
		edition, version, found := strings.Cut(strings.TrimSuffix(name, ".json"), "-")
		if !found {
			continue
		}
		ops, err := operationsIn(*historyDir, name)
		if err != nil {
			return err
		}
		if presence[edition] == nil {
			presence[edition] = map[string]map[operation]bool{}
		}
		presence[edition][version] = ops
	}
	if len(presence) == 0 {
		return fmt.Errorf("no specs found in %s", *historyDir)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by cmd/gen_applicability. DO NOT EDIT.\n\n")
	buf.WriteString("package apiversion\n\n")
	buf.WriteString(`import "github.com/jmrplens/portainer-mcp/internal/edition"` + "\n\n")
	buf.WriteString("var ranges = map[edition.Edition]map[Operation]Range{\n")

	var gaps []string
	for _, ed := range sortedKeys(presence) {
		versions := sortedKeys(presence[ed])
		sort.Slice(versions, func(i, j int) bool { return less(versions[i], versions[j]) })

		all := map[operation]bool{}
		for _, v := range versions {
			for op := range presence[ed][v] {
				all[op] = true
			}
		}

		constant := "edition.CE"
		if strings.EqualFold(ed, "ee") {
			constant = "edition.EE"
		}
		fmt.Fprintf(&buf, "\t%s: {\n", constant)

		ops := make([]operation, 0, len(all))
		for op := range all {
			ops = append(ops, op)
		}
		sort.Slice(ops, func(i, j int) bool {
			if ops[i].Path != ops[j].Path {
				return ops[i].Path < ops[j].Path
			}
			return ops[i].Method < ops[j].Method
		})

		for _, op := range ops {
			var indices []int
			for i, v := range versions {
				if presence[ed][v][op] {
					indices = append(indices, i)
				}
			}
			first, last := indices[0], indices[len(indices)-1]
			if len(indices) != last-first+1 {
				gaps = append(gaps, fmt.Sprintf("%s %s %s: present in %d of %d versions between %s and %s",
					ed, op.Method, op.Path, len(indices), last-first+1, versions[first], versions[last]))
			}
			maxVersion := ""
			if last != len(versions)-1 {
				maxVersion = versions[last]
			}
			fmt.Fprintf(&buf, "\t\t{Method: %q, Path: %q}: {MinVersion: %q, MaxVersion: %q},\n",
				op.Method, op.Path, versions[first], maxVersion)
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	for _, gap := range gaps {
		fmt.Fprintf(os.Stderr, "  gap: %s\n", gap)
	}
	fmt.Fprintf(os.Stderr, "%d operation(s) with non-contiguous presence\n", len(gaps))

	if err := os.WriteFile(*out, []byte(buf.String()), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", *out, err)
	}
	return nil
}

// operationsIn reads one spec file and returns the set of operations it
// documents. dir is the directory the caller listed name from: every entry is
// re-confined to dir before being opened, so a symlink or rename racing the
// os.ReadDir call cannot walk the read outside of it.
func operationsIn(dir, name string) (map[operation]bool, error) {
	path := filepath.Clean(filepath.Join(dir, name))
	if rel, err := filepath.Rel(dir, path); err != nil || strings.HasPrefix(rel, "..") {
		return nil, fmt.Errorf("refuse to read %s: escapes %s", path, dir)
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var doc struct {
		Paths map[string]map[string]json.RawMessage `json:"paths"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("decode %s: %w", path, err)
	}
	methods := map[string]bool{"get": true, "post": true, "put": true, "delete": true, "patch": true, "head": true, "options": true}
	ops := map[operation]bool{}
	for p, item := range doc.Paths {
		for method := range item {
			if methods[strings.ToLower(method)] {
				ops[operation{Method: strings.ToUpper(method), Path: p}] = true
			}
		}
	}
	return ops, nil
}

func less(a, b string) bool {
	fa, fb := strings.Split(a, "."), strings.Split(b, ".")
	for i := 0; i < len(fa) || i < len(fb); i++ {
		var x, y int
		if i < len(fa) {
			x, _ = strconv.Atoi(fa[i])
		}
		if i < len(fb) {
			y, _ = strconv.Atoi(fb[i])
		}
		if x != y {
			return x < y
		}
	}
	return false
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
