// Command gen_applicability derives per-operation version ranges from every
// published Portainer specification and writes them as Go source.
//
// Presence was measured as contiguous in semver order for 100 % of CE
// operations and 98 % of EE, with the three exceptions explained in the design
// specification. Any new gap this command finds is reported rather than
// smoothed over, because a gap means an operation was genuinely withdrawn and
// reintroduced.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/jmrplens/portainer-mcp/internal/specnaming"
)

type operation struct {
	Method string
	Path   string
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "gen_applicability: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	fs := flag.NewFlagSet("gen_applicability", flag.ContinueOnError)
	historyDir := fs.String("history", "api/specs/history", "directory of <edition>-<version>.json specs")
	out := fs.String("out", "internal/apiversion/applicability_gen.go", "file to write")
	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("parse flags: %w", err)
	}

	entries, err := os.ReadDir(*historyDir)
	if err != nil {
		return fmt.Errorf("read %s: %w", *historyDir, err)
	}

	// edition -> version -> set of operations
	presence := map[string]map[string]map[operation]bool{}
	// edition -> version -> operation -> operationId, for the versions in
	// which that operation carried a non-empty operationId.
	idsByVersion := map[string]map[string]map[operation]string{}
	for _, entry := range entries {
		name := entry.Name()
		if !strings.HasSuffix(name, ".json") || strings.Contains(name, "provenance") {
			continue
		}
		edition, version, found := strings.Cut(strings.TrimSuffix(name, ".json"), "-")
		if !found {
			continue
		}
		ops, ids, err := operationsIn(*historyDir, name)
		if err != nil {
			return err
		}
		if presence[edition] == nil {
			presence[edition] = map[string]map[operation]bool{}
			idsByVersion[edition] = map[string]map[operation]string{}
		}
		presence[edition][version] = ops
		idsByVersion[edition][version] = ids
	}
	if len(presence) == 0 {
		return fmt.Errorf("no specs found in %s", *historyDir)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by cmd/gen_applicability. DO NOT EDIT.\n\n")
	buf.WriteString("package apiversion\n\n")
	buf.WriteString(`import "github.com/jmrplens/portainer-mcp/internal/edition"` + "\n\n")
	buf.WriteString("var spans = map[edition.Edition]map[Operation][]Span{\n")

	var gaps []string
	// edition -> operationId -> operation, collected alongside spans so the
	// operationIDs map below can be emitted from data gathered in this same
	// pass over presence.
	opIDsByEdition := map[string]map[string]operation{}
	// edition -> every operation that edition documents in any version, kept
	// so borrowIDsAcrossEditions and applySyntheticIDs below can tell "this
	// edition serves the route but never named it" from "this edition does
	// not serve it".
	allByEdition := map[string]map[operation]bool{}
	for _, ed := range sortedKeys(presence) {
		versions := sortedKeys(presence[ed])
		sort.Slice(versions, func(i, j int) bool { return less(versions[i], versions[j]) })

		all := map[operation]bool{}
		for _, v := range versions {
			for op := range presence[ed][v] {
				all[op] = true
			}
		}
		allByEdition[ed] = all

		// Resolve each operation's operationId from the newest spec version in
		// which it carried a non-empty one: versions are visited oldest to
		// newest, and a later non-empty id always overwrites an earlier one, so
		// a renamed operationId resolves to its current name rather than a
		// stale one. The key is exported-Go-name form (first rune upper-cased)
		// rather than the raw spec string, because that is what oapi-codegen
		// names the generated method — the whole point of this index is to let
		// a caller resolve straight from that method name.
		byID := map[string]operation{}
		for _, v := range versions {
			for op, id := range idsByVersion[ed][v] {
				if id != "" {
					byID[exportedName(id)] = op
				}
			}
		}
		opIDsByEdition[ed] = byID

		constant := "edition.CE"
		if strings.EqualFold(ed, "ee") {
			constant = "edition.EE"
		}
		fmt.Fprintf(&buf, "\t%s: {\n", constant)

		ops := make([]operation, 0, len(all))
		for op := range all {
			ops = append(ops, op)
		}
		sort.Slice(ops, func(i, j int) bool {
			if ops[i].Path != ops[j].Path {
				return ops[i].Path < ops[j].Path
			}
			return ops[i].Method < ops[j].Method
		})

		for _, op := range ops {
			var indices []int
			for i, v := range versions {
				if presence[ed][v][op] {
					indices = append(indices, i)
				}
			}
			first, last := indices[0], indices[len(indices)-1]
			if len(indices) != last-first+1 {
				gaps = append(gaps, fmt.Sprintf("%s %s %s: present in %d of %d versions between %s and %s",
					ed, op.Method, op.Path, len(indices), last-first+1, versions[first], versions[last]))
			}

			// Emit one Span per contiguous run of indices, rather than
			// collapsing first-to-last into a single range: a withdrawn and
			// later reintroduced operation (e.g. /cloud/gitcredentials,
			// absent in 2.43.0, back in 2.44.0) must not be reported as
			// available on the version where it does not exist.
			var runs []string
			start := indices[0]
			prev := indices[0]
			for _, i := range indices[1:] {
				if i != prev+1 {
					runs = append(runs, spanLiteral(versions, start, prev))
					start = i
				}
				prev = i
			}
			runs = append(runs, spanLiteral(versions, start, prev))

			fmt.Fprintf(&buf, "\t\t{Method: %q, Path: %q}: {%s},\n",
				op.Method, op.Path, strings.Join(runs, ", "))
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	borrowed, err := borrowIDsAcrossEditions(allByEdition, opIDsByEdition)
	if err != nil {
		return err
	}

	// After borrowing, not before: a name some edition publishes is always
	// preferred to one this project invented, so the synthetic table only
	// ever sees the routes nothing anywhere names.
	synthesised, err := applySyntheticIDs(allByEdition, opIDsByEdition, specnaming.SyntheticOperationID)
	if err != nil {
		return err
	}

	buf.WriteString("\n// operationIDs maps an operation's OpenAPI operationId to the operation it\n")
	buf.WriteString("// identifies. oapi-codegen derives every generated Go method name from the\n")
	buf.WriteString("// operationId, so this is the only machine-checkable link between a generated\n")
	buf.WriteString("// method and its version applicability.\n")
	buf.WriteString("var operationIDs = map[edition.Edition]map[string]Operation{\n")
	for _, ed := range sortedKeys(presence) {
		constant := "edition.CE"
		if strings.EqualFold(ed, "ee") {
			constant = "edition.EE"
		}
		fmt.Fprintf(&buf, "\t%s: {\n", constant)

		ids := make([]string, 0, len(opIDsByEdition[ed]))
		for id := range opIDsByEdition[ed] {
			ids = append(ids, id)
		}
		sort.Strings(ids)

		for _, id := range ids {
			op := opIDsByEdition[ed][id]
			fmt.Fprintf(&buf, "\t\t%q: {Method: %q, Path: %q},\n", id, op.Method, op.Path)
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	for _, b := range borrowed {
		fmt.Fprintf(os.Stderr, "  borrowed id: %s\n", b)
	}
	fmt.Fprintf(os.Stderr, "%d operationId(s) borrowed across editions\n", len(borrowed))

	for _, s := range synthesised {
		fmt.Fprintf(os.Stderr, "  synthetic id: %s\n", s)
	}
	fmt.Fprintf(os.Stderr, "%d operationId(s) taken from internal/specnaming's table for routes no document names\n", len(synthesised))

	for _, gap := range gaps {
		fmt.Fprintf(os.Stderr, "  gap: %s\n", gap)
	}
	fmt.Fprintf(os.Stderr, "%d operation(s) with non-contiguous presence\n", len(gaps))

	if err := os.WriteFile(*out, []byte(buf.String()), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", *out, err)
	}
	return nil
}

// operationsIn reads one spec file and returns the set of operations it
// documents, plus the operationId each operation carries in this spec (a
// method+path with no operationId, or an empty one, is simply absent from the
// second map). dir is the directory the caller listed name from: every entry
// is re-confined to dir before being opened, so a symlink or rename racing the
// os.ReadDir call cannot walk the read outside of it.
func operationsIn(dir, name string) (map[operation]bool, map[operation]string, error) {
	path := filepath.Clean(filepath.Join(dir, name))
	if rel, err := filepath.Rel(dir, path); err != nil || strings.HasPrefix(rel, "..") {
		return nil, nil, fmt.Errorf("refuse to read %s: escapes %s", path, dir)
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, nil, fmt.Errorf("read %s: %w", path, err)
	}
	var doc struct {
		Paths map[string]map[string]json.RawMessage `json:"paths"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, nil, fmt.Errorf("decode %s: %w", path, err)
	}
	methods := map[string]bool{"get": true, "post": true, "put": true, "delete": true, "patch": true, "head": true, "options": true}
	ops := map[operation]bool{}
	ids := map[operation]string{}
	for p, item := range doc.Paths {
		for method, rawOp := range item {
			if !methods[strings.ToLower(method)] {
				continue
			}
			op := operation{Method: strings.ToUpper(method), Path: p}
			ops[op] = true

			var meta struct {
				OperationID string `json:"operationId"`
			}
			if err := json.Unmarshal(rawOp, &meta); err == nil && meta.OperationID != "" {
				ids[op] = meta.OperationID
			}
		}
	}
	return ops, ids, nil
}

// spanLiteral renders one contiguous run as a Span literal. A run that
// reaches the newest version leaves MaxVersion empty, meaning "still
// present".
func spanLiteral(versions []string, first, last int) string {
	maxVersion := ""
	if last != len(versions)-1 {
		maxVersion = versions[last]
	}
	return fmt.Sprintf("{MinVersion: %q, MaxVersion: %q}", versions[first], maxVersion)
}

func less(a, b string) bool {
	fa, fb := strings.Split(a, "."), strings.Split(b, ".")
	for i := 0; i < len(fa) || i < len(fb); i++ {
		var x, y int
		if i < len(fa) {
			x, _ = strconv.Atoi(fa[i])
		}
		if i < len(fb) {
			y, _ = strconv.Atoi(fb[i])
		}
		if x != y {
			return x < y
		}
	}
	return false
}

// exportedName converts a raw OpenAPI operationId (e.g. "systemStatus") to the
// exported Go identifier oapi-codegen derives from it ("SystemStatus"), by
// upper-casing the first rune. Every operationId in the vendored specs is a
// plain ASCII camelCase or PascalCase word with no separators, which is the
// only input oapi-codegen's own naming pass accepts, so that single-rune
// change is the whole transformation.
func exportedName(id string) string {
	if id == "" {
		return id
	}
	r := []rune(id)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// borrowIDsAcrossEditions gives an operation the operationId the *other*
// edition publishes for it, when this edition documents the same method and
// path but names it nothing.
//
// Portainer's Community specification omits the operationId on fourteen of
// its 265 operations, against one of Business's 442 — POST
// /endpoints/{id}/docker/v2/browse/put, GET and POST /webhooks and its three
// siblings, the four /websocket routes, POST /endpoint_groups, and two
// edge_agent routes. Every one of them is a fully documented operation:
// description, parameters, request body and responses are all there, and the
// route is served. Only the name is missing, and it has been missing in all
// thirty-eight vendored Community specifications, so this is a standing
// defect in the document rather than something a spec refresh will fix.
//
// It matters because operationIDs is the only index keyed by the name
// oapi-codegen gives a generated method, and internal/tools/actioncatalog
// resolves an action's edition through it: an operation absent from
// operationIDs[CE] reads as Business-exclusive, so a Community catalog would
// drop an action a Community server answers, and actioncatalog.Build would
// refuse a correct `Edition: edition.CE` declaration outright.
//
// The name is borrowed rather than invented, and only where this edition's
// own spans table already proves the route exists here: the (method, path)
// must be in this edition's operation set, unnamed by every one of this
// edition's specs, and named by some other edition. Nothing is written for a
// route an edition does not serve, and an edition that names an operation
// itself is never overridden. The vendored specifications are not modified —
// `make check-spec` still compares them against a fresh fetch, byte for byte.
//
// The one operation this cannot help is GET /endpoint_groups/{id}, which
// neither edition names; there is no name to borrow. applySyntheticIDs runs
// after this one and takes that route's name from internal/specnaming's
// explicit table instead.
func borrowIDsAcrossEditions(allByEdition map[string]map[operation]bool, opIDsByEdition map[string]map[string]operation) ([]string, error) {
	// operation -> the id some edition publishes for it.
	named := map[operation]string{}
	for _, ed := range sortedKeys(opIDsByEdition) {
		for id, op := range opIDsByEdition[ed] {
			named[op] = id
		}
	}

	var borrowed []string
	for _, ed := range sortedKeys(allByEdition) {
		own := map[operation]bool{}
		for _, op := range opIDsByEdition[ed] {
			own[op] = true
		}
		ops := make([]operation, 0, len(allByEdition[ed]))
		for op := range allByEdition[ed] {
			ops = append(ops, op)
		}
		sort.Slice(ops, func(i, j int) bool {
			if ops[i].Path != ops[j].Path {
				return ops[i].Path < ops[j].Path
			}
			return ops[i].Method < ops[j].Method
		})
		for _, op := range ops {
			if own[op] {
				continue
			}
			id, ok := named[op]
			if !ok {
				continue
			}
			// Never overwrite a name this edition already resolves. Two
			// operations sharing one operationId across editions cannot both
			// be right, and silently taking the borrowed one would move an
			// action's edition on the strength of a guess — the exact
			// failure mode this whole index exists to make impossible. No
			// vendored specification collides today; refusing rather than
			// picking is what keeps that true when one does.
			if existing, taken := opIDsByEdition[ed][id]; taken && existing != op {
				return nil, fmt.Errorf(
					"edition %s: operationId %q already resolves to %s %s, so it cannot be borrowed for %s %s; "+
						"one of the two vendored documents names the same operation for two different routes",
					ed, id, existing.Method, existing.Path, op.Method, op.Path)
			}
			opIDsByEdition[ed][id] = op
			borrowed = append(borrowed, fmt.Sprintf("%s %s %s -> %s", ed, op.Method, op.Path, id))
		}
	}
	return borrowed, nil
}

// applySyntheticIDs gives an operation the name internal/specnaming's table
// holds for it, when neither the edition's own documents nor any other
// edition's name it at all.
//
// This is borrowIDsAcrossEditions's last resort, and it runs after it for
// that reason: thirteen of Community's fourteen unnamed operations are named
// by the Business document, and a borrowed name — one Portainer itself
// publishes — is always to be preferred to one this project decided on. What
// is left is the route *neither* document names, GET /endpoint_groups/{id},
// which both editions serve and which therefore has no name to borrow. Until
// this pass existed it stayed absent from operationIDs in both editions, and
// since internal/tools/actioncatalog resolves an action's edition through
// that index, actioncatalog.Build refused any action carrying it as
// "resolves in neither edition" — so the route could not be declared at all,
// however the domain package was written.
//
// nameFor is a parameter rather than a direct call to
// specnaming.SyntheticOperationID so that a test can drive this with a
// synthetic table as well as the real one. A test asserting only what the
// real single-entry table produces would pass just as happily against an
// implementation that hardcoded that one entry, or against one that never
// consulted a table at all — the same reason resolveActionName in
// cmd/gen_action_inputs takes its override table as an argument.
//
// Nothing is written for a route an edition does not serve: the (method,
// path) must be in this edition's own operation set, gathered from that
// edition's documents' paths. An edition that already resolves the name —
// its own or a borrowed one — is never overridden.
func applySyntheticIDs(
	allByEdition map[string]map[operation]bool,
	opIDsByEdition map[string]map[string]operation,
	nameFor func(method, path string) (string, bool),
) ([]string, error) {
	var synthesised []string
	for _, ed := range sortedKeys(allByEdition) {
		own := map[operation]bool{}
		for _, op := range opIDsByEdition[ed] {
			own[op] = true
		}
		ops := make([]operation, 0, len(allByEdition[ed]))
		for op := range allByEdition[ed] {
			ops = append(ops, op)
		}
		sort.Slice(ops, func(i, j int) bool {
			if ops[i].Path != ops[j].Path {
				return ops[i].Path < ops[j].Path
			}
			return ops[i].Method < ops[j].Method
		})
		for _, op := range ops {
			if own[op] {
				continue
			}
			id, ok := nameFor(op.Method, op.Path)
			if !ok {
				continue
			}
			// Refuse rather than overwrite, exactly as borrowing does. A
			// synthetic name colliding with one a document publishes would
			// move an action's edition on the strength of a name this
			// project invented, which is worse than the gap it was invented
			// to close. The table records that no collision existed when
			// each entry was written; this is what keeps that true when a
			// future specification names something new.
			if existing, taken := opIDsByEdition[ed][id]; taken && existing != op {
				return nil, fmt.Errorf(
					"edition %s: operationId %q already resolves to %s %s, so internal/specnaming's synthetic name for %s %s cannot be used; "+
						"a vendored document now names an operation this project had to name itself — remove the table entry",
					ed, id, existing.Method, existing.Path, op.Method, op.Path)
			}
			if opIDsByEdition[ed] == nil {
				opIDsByEdition[ed] = map[string]operation{}
			}
			opIDsByEdition[ed][id] = op
			synthesised = append(synthesised, fmt.Sprintf("%s %s %s -> %s", ed, op.Method, op.Path, id))
		}
	}
	return synthesised, nil
}
