// Command gen_applicability derives per-operation version ranges from every
// published Portainer specification and writes them as Go source.
//
// Presence was measured as contiguous in semver order for 100 % of CE
// operations and 98 % of EE, with the three exceptions explained in the design
// specification. Any new gap this command finds is reported rather than
// smoothed over, because a gap means an operation was genuinely withdrawn and
// reintroduced.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

type operation struct {
	Method string
	Path   string
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "gen_applicability: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	fs := flag.NewFlagSet("gen_applicability", flag.ContinueOnError)
	historyDir := fs.String("history", "api/specs/history", "directory of <edition>-<version>.json specs")
	out := fs.String("out", "internal/apiversion/applicability_gen.go", "file to write")
	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("parse flags: %w", err)
	}

	entries, err := os.ReadDir(*historyDir)
	if err != nil {
		return fmt.Errorf("read %s: %w", *historyDir, err)
	}

	// edition -> version -> set of operations
	presence := map[string]map[string]map[operation]bool{}
	// edition -> version -> operation -> operationId, for the versions in
	// which that operation carried a non-empty operationId.
	idsByVersion := map[string]map[string]map[operation]string{}
	for _, entry := range entries {
		name := entry.Name()
		if !strings.HasSuffix(name, ".json") || strings.Contains(name, "provenance") {
			continue
		}
		edition, version, found := strings.Cut(strings.TrimSuffix(name, ".json"), "-")
		if !found {
			continue
		}
		ops, ids, err := operationsIn(*historyDir, name)
		if err != nil {
			return err
		}
		if presence[edition] == nil {
			presence[edition] = map[string]map[operation]bool{}
			idsByVersion[edition] = map[string]map[operation]string{}
		}
		presence[edition][version] = ops
		idsByVersion[edition][version] = ids
	}
	if len(presence) == 0 {
		return fmt.Errorf("no specs found in %s", *historyDir)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by cmd/gen_applicability. DO NOT EDIT.\n\n")
	buf.WriteString("package apiversion\n\n")
	buf.WriteString(`import "github.com/jmrplens/portainer-mcp/internal/edition"` + "\n\n")
	buf.WriteString("var spans = map[edition.Edition]map[Operation][]Span{\n")

	var gaps []string
	// edition -> operationId -> operation, collected alongside spans so the
	// operationIDs map below can be emitted from data gathered in this same
	// pass over presence.
	opIDsByEdition := map[string]map[string]operation{}
	for _, ed := range sortedKeys(presence) {
		versions := sortedKeys(presence[ed])
		sort.Slice(versions, func(i, j int) bool { return less(versions[i], versions[j]) })

		all := map[operation]bool{}
		for _, v := range versions {
			for op := range presence[ed][v] {
				all[op] = true
			}
		}

		// Resolve each operation's operationId from the newest spec version in
		// which it carried a non-empty one: versions are visited oldest to
		// newest, and a later non-empty id always overwrites an earlier one, so
		// a renamed operationId resolves to its current name rather than a
		// stale one. The key is exported-Go-name form (first rune upper-cased)
		// rather than the raw spec string, because that is what oapi-codegen
		// names the generated method — the whole point of this index is to let
		// a caller resolve straight from that method name.
		byID := map[string]operation{}
		for _, v := range versions {
			for op, id := range idsByVersion[ed][v] {
				if id != "" {
					byID[exportedName(id)] = op
				}
			}
		}
		opIDsByEdition[ed] = byID

		constant := "edition.CE"
		if strings.EqualFold(ed, "ee") {
			constant = "edition.EE"
		}
		fmt.Fprintf(&buf, "\t%s: {\n", constant)

		ops := make([]operation, 0, len(all))
		for op := range all {
			ops = append(ops, op)
		}
		sort.Slice(ops, func(i, j int) bool {
			if ops[i].Path != ops[j].Path {
				return ops[i].Path < ops[j].Path
			}
			return ops[i].Method < ops[j].Method
		})

		for _, op := range ops {
			var indices []int
			for i, v := range versions {
				if presence[ed][v][op] {
					indices = append(indices, i)
				}
			}
			first, last := indices[0], indices[len(indices)-1]
			if len(indices) != last-first+1 {
				gaps = append(gaps, fmt.Sprintf("%s %s %s: present in %d of %d versions between %s and %s",
					ed, op.Method, op.Path, len(indices), last-first+1, versions[first], versions[last]))
			}

			// Emit one Span per contiguous run of indices, rather than
			// collapsing first-to-last into a single range: a withdrawn and
			// later reintroduced operation (e.g. /cloud/gitcredentials,
			// absent in 2.43.0, back in 2.44.0) must not be reported as
			// available on the version where it does not exist.
			var runs []string
			start := indices[0]
			prev := indices[0]
			for _, i := range indices[1:] {
				if i != prev+1 {
					runs = append(runs, spanLiteral(versions, start, prev))
					start = i
				}
				prev = i
			}
			runs = append(runs, spanLiteral(versions, start, prev))

			fmt.Fprintf(&buf, "\t\t{Method: %q, Path: %q}: {%s},\n",
				op.Method, op.Path, strings.Join(runs, ", "))
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	buf.WriteString("\n// operationIDs maps an operation's OpenAPI operationId to the operation it\n")
	buf.WriteString("// identifies. oapi-codegen derives every generated Go method name from the\n")
	buf.WriteString("// operationId, so this is the only machine-checkable link between a generated\n")
	buf.WriteString("// method and its version applicability.\n")
	buf.WriteString("var operationIDs = map[edition.Edition]map[string]Operation{\n")
	for _, ed := range sortedKeys(presence) {
		constant := "edition.CE"
		if strings.EqualFold(ed, "ee") {
			constant = "edition.EE"
		}
		fmt.Fprintf(&buf, "\t%s: {\n", constant)

		ids := make([]string, 0, len(opIDsByEdition[ed]))
		for id := range opIDsByEdition[ed] {
			ids = append(ids, id)
		}
		sort.Strings(ids)

		for _, id := range ids {
			op := opIDsByEdition[ed][id]
			fmt.Fprintf(&buf, "\t\t%q: {Method: %q, Path: %q},\n", id, op.Method, op.Path)
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	for _, gap := range gaps {
		fmt.Fprintf(os.Stderr, "  gap: %s\n", gap)
	}
	fmt.Fprintf(os.Stderr, "%d operation(s) with non-contiguous presence\n", len(gaps))

	if err := os.WriteFile(*out, []byte(buf.String()), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", *out, err)
	}
	return nil
}

// operationsIn reads one spec file and returns the set of operations it
// documents, plus the operationId each operation carries in this spec (a
// method+path with no operationId, or an empty one, is simply absent from the
// second map). dir is the directory the caller listed name from: every entry
// is re-confined to dir before being opened, so a symlink or rename racing the
// os.ReadDir call cannot walk the read outside of it.
func operationsIn(dir, name string) (map[operation]bool, map[operation]string, error) {
	path := filepath.Clean(filepath.Join(dir, name))
	if rel, err := filepath.Rel(dir, path); err != nil || strings.HasPrefix(rel, "..") {
		return nil, nil, fmt.Errorf("refuse to read %s: escapes %s", path, dir)
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, nil, fmt.Errorf("read %s: %w", path, err)
	}
	var doc struct {
		Paths map[string]map[string]json.RawMessage `json:"paths"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, nil, fmt.Errorf("decode %s: %w", path, err)
	}
	methods := map[string]bool{"get": true, "post": true, "put": true, "delete": true, "patch": true, "head": true, "options": true}
	ops := map[operation]bool{}
	ids := map[operation]string{}
	for p, item := range doc.Paths {
		for method, rawOp := range item {
			if !methods[strings.ToLower(method)] {
				continue
			}
			op := operation{Method: strings.ToUpper(method), Path: p}
			ops[op] = true

			var meta struct {
				OperationID string `json:"operationId"`
			}
			if err := json.Unmarshal(rawOp, &meta); err == nil && meta.OperationID != "" {
				ids[op] = meta.OperationID
			}
		}
	}
	return ops, ids, nil
}

// spanLiteral renders one contiguous run as a Span literal. A run that
// reaches the newest version leaves MaxVersion empty, meaning "still
// present".
func spanLiteral(versions []string, first, last int) string {
	maxVersion := ""
	if last != len(versions)-1 {
		maxVersion = versions[last]
	}
	return fmt.Sprintf("{MinVersion: %q, MaxVersion: %q}", versions[first], maxVersion)
}

func less(a, b string) bool {
	fa, fb := strings.Split(a, "."), strings.Split(b, ".")
	for i := 0; i < len(fa) || i < len(fb); i++ {
		var x, y int
		if i < len(fa) {
			x, _ = strconv.Atoi(fa[i])
		}
		if i < len(fb) {
			y, _ = strconv.Atoi(fb[i])
		}
		if x != y {
			return x < y
		}
	}
	return false
}

// exportedName converts a raw OpenAPI operationId (e.g. "systemStatus") to the
// exported Go identifier oapi-codegen derives from it ("SystemStatus"), by
// upper-casing the first rune. Every operationId in the vendored specs is a
// plain ASCII camelCase or PascalCase word with no separators, which is the
// only input oapi-codegen's own naming pass accepts, so that single-rune
// change is the whole transformation.
func exportedName(id string) string {
	if id == "" {
		return id
	}
	r := []rune(id)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
