package harness

import (
	"crypto/tls"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"net/http"
	"time"
)

// ClientWithCA builds an http.Client that verifies its peer against caPEM
// instead of skipping verification.
//
// The Kubernetes leg's Helm chart deploys Portainer with a self-signed
// certificate, but self-signed is not the same as unverifiable: the
// certificate is a fixed, known value once read out of the running pod (see
// k3d-up.sh), and pinning it as the sole trusted root lets the client verify
// the real certificate rather than accept anything with a valid-looking
// handshake. serverName is taken from the certificate's own Subject
// Alternative Name rather than assumed — the certificate is generated by
// Portainer at pod startup, not by this project, and nothing here should
// hardcode what it happens to put there — which is also what makes
// connecting by the pod's IP address compatible with verifying by name: the
// TLS ServerName sent during the handshake does not have to match how the
// connection was dialled.
func ClientWithCA(caPEM []byte, timeout time.Duration) (*http.Client, error) {
	block, _ := pem.Decode(caPEM)
	if block == nil {
		return nil, fmt.Errorf("decode certificate: no PEM block found")
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse certificate: %w", err)
	}
	if len(cert.DNSNames) == 0 {
		return nil, fmt.Errorf("certificate carries no DNS name to verify against")
	}

	pool := x509.NewCertPool()
	pool.AddCert(cert)

	transport := http.DefaultTransport.(*http.Transport).Clone()
	transport.TLSClientConfig = &tls.Config{
		RootCAs:    pool,
		ServerName: cert.DNSNames[0],
		MinVersion: tls.VersionTLS12,
	}
	return &http.Client{Timeout: timeout, Transport: transport}, nil
}
