// Code generated by cmd/gen_action_inputs from api/specs/ee-2.44.0.json. DO NOT EDIT.

package tags

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/jmrplens/portainer-mcp/internal/edition"
	"github.com/jmrplens/portainer-mcp/internal/portainer"
	apigen "github.com/jmrplens/portainer-mcp/internal/portainer/gen"
	"github.com/jmrplens/portainer-mcp/internal/toolutil"
)

// tagCreate is the generated handler for operation TagCreate.
func tagCreate(ctx context.Context, c *portainer.Client, input json.RawMessage) (any, error) {
	var body apigen.TagCreateJSONRequestBody
	if err := json.Unmarshal(input, &body); err != nil {
		return nil, fmt.Errorf("TagCreate: parse request body: %w", err)
	}
	resp, err := c.API.TagCreateWithResponse(ctx, body)
	if err != nil {
		return nil, fmt.Errorf("TagCreate: %w", err)
	}
	if err := toolutil.Check(resp); err != nil {
		return nil, fmt.Errorf("TagCreate: %w", err)
	}
	return resp.JSON200, nil
}

// tagList is the generated handler for operation TagList.
func tagList(ctx context.Context, c *portainer.Client, _ json.RawMessage) (any, error) {
	resp, err := c.API.TagListWithResponse(ctx)
	if err != nil {
		return nil, fmt.Errorf("TagList: %w", err)
	}
	if err := toolutil.Check(resp); err != nil {
		return nil, fmt.Errorf("TagList: %w", err)
	}
	return resp.JSON200, nil
}

// generatedSpecs returns every ActionSpec this generator derives for this
// domain. The domain's own Specs() (in its own, non-generated file) combines
// this with whatever action this generator refused or the domain otherwise
// declares by hand.
func generatedSpecs() []toolutil.ActionSpec {
	return []toolutil.ActionSpec{
		toolutil.WithNarrative(toolutil.ActionSpec{
			Name: "tags.create", Domain: "tags", OperationID: "TagCreate",
			Title:       "Create a new tag",
			Description: "Create a new tag.",
			Edition:     edition.CE,
			Mutating:    true,
			Handler:     tagCreate,
			Input:       tagCreateInput{},
		}, narrative("TagCreate")),
		toolutil.WithNarrative(toolutil.ActionSpec{
			Name: "tags.list", Domain: "tags", OperationID: "TagList",
			Title:       "List tags",
			Description: "List tags.",
			Edition:     edition.CE,
			Handler:     tagList,
		}, narrative("TagList")),
	}
}
