// Code generated by cmd/gen_action_inputs from api/specs/ee-2.44.0.json. DO NOT EDIT.

package tags

// tagCreateInput is the parameter shape for operation TagCreate (POST /tags).
type tagCreateInput struct {
	Name string `json:"name"`
}

// tagDeleteInput is the parameter shape for operation TagDelete (DELETE /tags/{id}).
type tagDeleteInput struct {
	// ID Tag identifier
	ID int `json:"id"`
}
