// Code generated by cmd/gen_action_inputs from api/specs/ee-2.44.0.json. DO NOT EDIT.

package system

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/jmrplens/portainer-mcp/internal/edition"
	"github.com/jmrplens/portainer-mcp/internal/portainer"
	"github.com/jmrplens/portainer-mcp/internal/toolutil"
)

// systemInfo is the generated handler for operation SystemInfo.
func systemInfo(ctx context.Context, c *portainer.Client, _ json.RawMessage) (any, error) {
	resp, err := c.API.SystemInfoWithResponse(ctx)
	if err != nil {
		return nil, fmt.Errorf("SystemInfo: %w", err)
	}
	if err := toolutil.Check(resp); err != nil {
		return nil, fmt.Errorf("SystemInfo: %w", err)
	}
	return resp.JSON200, nil
}

// systemNodesCount is the generated handler for operation SystemNodesCount.
func systemNodesCount(ctx context.Context, c *portainer.Client, _ json.RawMessage) (any, error) {
	resp, err := c.API.SystemNodesCountWithResponse(ctx)
	if err != nil {
		return nil, fmt.Errorf("SystemNodesCount: %w", err)
	}
	if err := toolutil.Check(resp); err != nil {
		return nil, fmt.Errorf("SystemNodesCount: %w", err)
	}
	return resp.JSON200, nil
}

// systemStatus is the generated handler for operation SystemStatus.
func systemStatus(ctx context.Context, c *portainer.Client, _ json.RawMessage) (any, error) {
	resp, err := c.API.SystemStatusWithResponse(ctx)
	if err != nil {
		return nil, fmt.Errorf("SystemStatus: %w", err)
	}
	if err := toolutil.Check(resp); err != nil {
		return nil, fmt.Errorf("SystemStatus: %w", err)
	}
	return resp.JSON200, nil
}

// systemUpdate is the generated handler for operation SystemUpdate.
func systemUpdate(ctx context.Context, c *portainer.Client, _ json.RawMessage) (any, error) {
	resp, err := c.API.SystemUpdateWithResponse(ctx)
	if err != nil {
		return nil, fmt.Errorf("SystemUpdate: %w", err)
	}
	if err := toolutil.Check(resp); err != nil {
		return nil, fmt.Errorf("SystemUpdate: %w", err)
	}
	return resp.JSON204, nil
}

// systemVersion is the generated handler for operation SystemVersion.
func systemVersion(ctx context.Context, c *portainer.Client, _ json.RawMessage) (any, error) {
	resp, err := c.API.SystemVersionWithResponse(ctx)
	if err != nil {
		return nil, fmt.Errorf("SystemVersion: %w", err)
	}
	if err := toolutil.Check(resp); err != nil {
		return nil, fmt.Errorf("SystemVersion: %w", err)
	}
	return resp.JSON200, nil
}

// generatedSpecs returns every ActionSpec this generator derives for this
// domain. The domain's own Specs() (in its own, non-generated file) combines
// this with whatever action this generator refused or the domain otherwise
// declares by hand.
func generatedSpecs() []toolutil.ActionSpec {
	return []toolutil.ActionSpec{
		toolutil.WithNarrative(toolutil.ActionSpec{
			Name: "system.info", Domain: "system", OperationID: "SystemInfo",
			Title:       "Retrieve system info",
			Description: "Retrieve system info",
			Edition:     edition.CE,
			Handler:     systemInfo,
		}, narrative("SystemInfo")),
		toolutil.WithNarrative(toolutil.ActionSpec{
			Name: "system.nodes_count", Domain: "system", OperationID: "SystemNodesCount",
			Title:       "Retrieve the count of nodes",
			Description: "Retrieve the count of nodes",
			Edition:     edition.CE,
			Handler:     systemNodesCount,
		}, narrative("SystemNodesCount")),
		toolutil.WithNarrative(toolutil.ActionSpec{
			Name: "system.status", Domain: "system", OperationID: "SystemStatus",
			Title:       "Check Portainer status",
			Description: "Retrieve Portainer status",
			Edition:     edition.CE,
			Handler:     systemStatus,
		}, narrative("SystemStatus")),
		toolutil.WithNarrative(toolutil.ActionSpec{
			Name: "system.update", Domain: "system", OperationID: "SystemUpdate",
			Title:       "Update Portainer to latest version",
			Description: "Update Portainer to latest version",
			Edition:     edition.EE,
			Mutating:    true,
			Handler:     systemUpdate,
		}, narrative("SystemUpdate")),
		toolutil.WithNarrative(toolutil.ActionSpec{
			Name: "system.version", Domain: "system", OperationID: "SystemVersion",
			Title:       "Check for portainer updates",
			Description: "Check if portainer has an update available",
			Edition:     edition.CE,
			Handler:     systemVersion,
		}, narrative("SystemVersion")),
	}
}
