// Code generated by cmd/gen_action_inputs from api/specs/ee-2.44.0.json. DO NOT EDIT.

package registries

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/jmrplens/portainer-mcp/internal/edition"
	"github.com/jmrplens/portainer-mcp/internal/portainer"
	apigen "github.com/jmrplens/portainer-mcp/internal/portainer/gen"
	"github.com/jmrplens/portainer-mcp/internal/toolutil"
)

// registryCreate is the generated handler for operation RegistryCreate.
func registryCreate(ctx context.Context, c *portainer.Client, input json.RawMessage) (any, error) {
	var body apigen.RegistryCreateJSONRequestBody
	if err := json.Unmarshal(input, &body); err != nil {
		return nil, fmt.Errorf("RegistryCreate: parse request body: %w", err)
	}
	resp, err := c.API.RegistryCreateWithResponse(ctx, body)
	if err != nil {
		return nil, fmt.Errorf("RegistryCreate: %w", err)
	}
	if err := toolutil.Check(resp); err != nil {
		return nil, fmt.Errorf("RegistryCreate: %w", err)
	}
	return redactRegistryCreate(resp.JSON200), nil
}

// registryList is the generated handler for operation RegistryList.
func registryList(ctx context.Context, c *portainer.Client, _ json.RawMessage) (any, error) {
	resp, err := c.API.RegistryListWithResponse(ctx)
	if err != nil {
		return nil, fmt.Errorf("RegistryList: %w", err)
	}
	if err := toolutil.Check(resp); err != nil {
		return nil, fmt.Errorf("RegistryList: %w", err)
	}
	return redactRegistryList(resp.JSON200), nil
}

// registryPing is the generated handler for operation RegistryPing.
func registryPing(ctx context.Context, c *portainer.Client, input json.RawMessage) (any, error) {
	var body apigen.RegistryPingJSONRequestBody
	if err := json.Unmarshal(input, &body); err != nil {
		return nil, fmt.Errorf("RegistryPing: parse request body: %w", err)
	}
	resp, err := c.API.RegistryPingWithResponse(ctx, body)
	if err != nil {
		return nil, fmt.Errorf("RegistryPing: %w", err)
	}
	if err := toolutil.Check(resp); err != nil {
		return nil, fmt.Errorf("RegistryPing: %w", err)
	}
	return resp.JSON200, nil
}

// generatedSpecs returns every ActionSpec this generator derives for this
// domain. The domain's own Specs() (in its own, non-generated file) combines
// this with whatever action this generator refused or the domain otherwise
// declares by hand.
func generatedSpecs() []toolutil.ActionSpec {
	return []toolutil.ActionSpec{
		toolutil.WithNarrative(toolutil.ActionSpec{
			Name: "registries.create", Domain: "registries", OperationID: "RegistryCreate",
			Title:       "Create a new registry",
			Description: "Create a new registry.",
			Edition:     edition.CE,
			Mutating:    true,
			Handler:     registryCreate,
			Input:       registryCreateInput{},
		}, narrative("RegistryCreate")),
		toolutil.WithNarrative(toolutil.ActionSpec{
			Name: "registries.list", Domain: "registries", OperationID: "RegistryList",
			Title:       "List Registries",
			Description: "List all registries.\nAdministrators and edge-admins receive the full registry record (minus passwords).\nAll other authenticated users receive a scrubbed record containing only ID, Name, and Type.",
			Edition:     edition.CE,
			Handler:     registryList,
		}, narrative("RegistryList")),
		toolutil.WithNarrative(toolutil.ActionSpec{
			Name: "registries.ping", Domain: "registries", OperationID: "RegistryPing",
			Title:       "Test registry connection",
			Description: "Test connection to a registry with provided credentials",
			Edition:     edition.CE,
			Mutating:    true,
			Handler:     registryPing,
			Input:       registryPingInput{},
		}, narrative("RegistryPing")),
	}
}
