// Code generated by cmd/gen_action_inputs from api/specs/ee-2.44.0.json. DO NOT EDIT.

package registries

// ecrDeleteRepositoryInput is the parameter shape for operation EcrDeleteRepository (DELETE /registries/{id}/ecr/repositories/{repositoryName}).
type ecrDeleteRepositoryInput struct {
	// ID Registry identifier
	ID int `json:"id"`
	// RepositoryName Repository name
	RepositoryName string `json:"repositoryName"`
}

func (ecrDeleteRepositoryInput) MinimumParams() map[string]int {
	return map[string]int{
		"id": 1,
	}
}

// ecrDeleteTagsInput is the parameter shape for operation EcrDeleteTags (DELETE /registries/{id}/ecr/repositories/{repositoryName}/tags).
type ecrDeleteTagsInput struct {
	// ID Registry identifier
	ID int `json:"id"`
	// RepositoryName Repository name
	RepositoryName int      `json:"repositoryName"`
	Tags           []string `json:"tags,omitempty"`
}

func (ecrDeleteTagsInput) MinimumParams() map[string]int {
	return map[string]int{
		"id": 1,
	}
}

// registryConfigureInput is the parameter shape for operation RegistryConfigure (POST /registries/{id}/configure).
type registryConfigureInput struct {
	// Authentication Is authentication against this registry enabled
	Authentication bool `json:"authentication"`
	// ID Registry identifier
	ID int `json:"id"`
	// Password Password used to authenticate against this registry. required when Authentication is true
	Password *string `json:"password,omitempty"`
	// Region ECR region
	Region *string `json:"region,omitempty"`
	// TLS Use TLS
	TLS *bool `json:"tls,omitempty"`
	// TLSCACertFile The TLS CA certificate file
	TLSCACertFile []int `json:"tlsCACertFile,omitempty"`
	// TLSCertFile The TLS client certificate file
	TLSCertFile []int `json:"tlsCertFile,omitempty"`
	// TLSKeyFile The TLS client key file
	TLSKeyFile []int `json:"tlsKeyFile,omitempty"`
	// TLSSkipVerify Skip the verification of the server TLS certificate
	TLSSkipVerify *bool `json:"tlsSkipVerify,omitempty"`
	// Username Username used to authenticate against this registry. Required when Authentication is true
	Username *string `json:"username,omitempty"`
}

func (registryConfigureInput) MinimumParams() map[string]int {
	return map[string]int{
		"id": 1,
	}
}

// registryCreateInput is the parameter shape for operation RegistryCreate (POST /registries).
type registryCreateInput struct {
	// Authentication Is authentication against this registry enabled
	Authentication bool `json:"authentication"`
	// BaseURL BaseURL required for ProGet registry
	BaseURL *string `json:"baseUrl,omitempty"`
	// Ecr ECR specific details, required when type = 7
	Ecr *registryCreateInputEcr `json:"ecr,omitempty"`
	// Github Github specific details, required when type = 8
	Github *registryCreateInputGithub `json:"github,omitempty"`
	// Gitlab Gitlab specific details, required when type = 4
	Gitlab *registryCreateInputGitlab `json:"gitlab,omitempty"`
	// Name Name that will be used to identify this registry
	Name string `json:"name"`
	// Password Password used to authenticate against this registry. required when Authentication is true
	Password *string `json:"password,omitempty"`
	// Quay Quay specific details, required when type = 1
	Quay *registryCreateInputQuay `json:"quay,omitempty"`
	// TLS Use TLS
	TLS *bool `json:"tls,omitempty"`
	// Type Registry Type. Valid values are:
	// 	1 (Quay.io),
	// 	2 (Azure container registry),
	// 	3 (custom registry),
	// 	4 (Gitlab registry),
	// 	5 (ProGet registry),
	// 	6 (DockerHub)
	// 	7 (ECR)
	// 	8 (Github registry)
	Type int `json:"type"`
	// URL URL or IP address of the Docker registry
	URL string `json:"url"`
	// Username Username used to authenticate against this registry. Required when Authentication is true
	Username *string `json:"username,omitempty"`
}

func (registryCreateInput) EnumParams() map[string][]any {
	return map[string][]any{
		"type": {1, 2, 3, 4, 5, 6, 7, 8},
	}
}

// registryCreateInputEcr: ECR specific details, required when type = 7
type registryCreateInputEcr struct {
	Region *string `json:"region,omitempty"`
}

// registryCreateInputGithub: Github specific details, required when type = 8
type registryCreateInputGithub struct {
	OrganisationName *string `json:"organisationName,omitempty"`
	UseOrganisation  *bool   `json:"useOrganisation,omitempty"`
}

// registryCreateInputGitlab: Gitlab specific details, required when type = 4
type registryCreateInputGitlab struct {
	InstanceURL *string `json:"instanceUrl,omitempty"`
	ProjectID   *int    `json:"projectId,omitempty"`
	ProjectPath *string `json:"projectPath,omitempty"`
}

// registryCreateInputQuay: Quay specific details, required when type = 1
type registryCreateInputQuay struct {
	OrganisationName *string `json:"organisationName,omitempty"`
	UseOrganisation  *bool   `json:"useOrganisation,omitempty"`
}

// registryDeleteInput is the parameter shape for operation RegistryDelete (DELETE /registries/{id}).
type registryDeleteInput struct {
	// ID Registry identifier
	ID int `json:"id"`
}

func (registryDeleteInput) MinimumParams() map[string]int {
	return map[string]int{
		"id": 1,
	}
}

// registryInspectInput is the parameter shape for operation RegistryInspect (GET /registries/{id}).
type registryInspectInput struct {
	// EndpointID Environment identifier (applies policy overrides if provided)
	EndpointID *int `json:"endpointId,omitempty"`
	// ID Registry identifier
	ID int `json:"id"`
}

func (registryInspectInput) MinimumParams() map[string]int {
	return map[string]int{
		"id": 1,
	}
}

// registryPingInput is the parameter shape for operation RegistryPing (POST /registries/ping).
type registryPingInput struct {
	// Password Password used to authenticate against this registry
	Password *string `json:"password,omitempty"`
	// TLS Use TLS
	TLS *bool `json:"tls,omitempty"`
	// Type Registry Type. Valid values are:
	// 	1 (Quay.io),
	// 	2 (Azure container registry),
	// 	3 (custom registry),
	// 	4 (Gitlab registry),
	// 	5 (ProGet registry),
	// 	6 (DockerHub)
	// 	7 (ECR)
	// 	8 (Github registry)
	Type int `json:"type"`
	// URL URL or IP address of the Docker registry
	URL string `json:"url"`
	// Username Username used to authenticate against this registry
	Username *string `json:"username,omitempty"`
}

func (registryPingInput) EnumParams() map[string][]any {
	return map[string][]any{
		"type": {1, 2, 3, 4, 5, 6, 7, 8},
	}
}

// registryUpdateInput is the parameter shape for operation RegistryUpdate (PUT /registries/{id}).
type registryUpdateInput struct {
	Authentication bool                       `json:"authentication"`
	BaseURL        *string                    `json:"baseUrl,omitempty"`
	Ecr            *registryUpdateInputEcr    `json:"ecr,omitempty"`
	Github         *registryUpdateInputGithub `json:"github,omitempty"`
	// ID Registry identifier
	ID               int                                                 `json:"id"`
	Name             string                                              `json:"name"`
	Password         *string                                             `json:"password,omitempty"`
	Quay             *registryUpdateInputQuay                            `json:"quay,omitempty"`
	RegistryAccesses map[string]registryUpdateInputRegistryAccessesValue `json:"registryAccesses,omitempty"`
	URL              string                                              `json:"url"`
	Username         *string                                             `json:"username,omitempty"`
}

func (registryUpdateInput) MinimumParams() map[string]int {
	return map[string]int{
		"id": 1,
	}
}

// registryUpdateInputEcr is a nested object property.
type registryUpdateInputEcr struct {
	Region *string `json:"region,omitempty"`
}

// registryUpdateInputGithub is a nested object property.
type registryUpdateInputGithub struct {
	OrganisationName *string `json:"organisationName,omitempty"`
	UseOrganisation  *bool   `json:"useOrganisation,omitempty"`
}

// registryUpdateInputQuay is a nested object property.
type registryUpdateInputQuay struct {
	OrganisationName *string `json:"organisationName,omitempty"`
	UseOrganisation  *bool   `json:"useOrganisation,omitempty"`
}

// registryUpdateInputRegistryAccessesValueTeamAccessPoliciesValue is a nested object property.
type registryUpdateInputRegistryAccessesValueTeamAccessPoliciesValue struct {
	// Namespaces Namespaces is a list of namespaces that this access policy applies to. Only used for namespaced level roles
	Namespaces []string `json:"namespaces,omitempty"`
	// RoleID Role identifier. Reference the role that will be associated to this access policy
	RoleID int `json:"roleId"`
}

// registryUpdateInputRegistryAccessesValueUserAccessPoliciesValue is a nested object property.
type registryUpdateInputRegistryAccessesValueUserAccessPoliciesValue struct {
	// Namespaces Namespaces is a list of namespaces that this access policy applies to. Only used for namespaced level roles
	Namespaces []string `json:"namespaces,omitempty"`
	// RoleID Role identifier. Reference the role that will be associated to this access policy
	RoleID int `json:"roleId"`
}

// registryUpdateInputRegistryAccessesValue is a nested object property.
type registryUpdateInputRegistryAccessesValue struct {
	// Namespaces Kubernetes specific fields (with kubernetes, namespaces have access to a registry, if users/teams have access to the same namespace, they have access to the registry)
	Namespaces         []string                                                                   `json:"namespaces,omitempty"`
	TeamAccessPolicies map[string]registryUpdateInputRegistryAccessesValueTeamAccessPoliciesValue `json:"teamAccessPolicies,omitempty"`
	// UserAccessPolicies Docker specific fields (with docker, users/teams have access to a registry)
	UserAccessPolicies map[string]registryUpdateInputRegistryAccessesValueUserAccessPoliciesValue `json:"userAccessPolicies,omitempty"`
}

// repositoryTagsDeleteInput is the parameter shape for operation RepositoryTagsDelete (DELETE /registries/{id}/repositories/{repositoryName}/tags).
type repositoryTagsDeleteInput struct {
	// ID Registry identifier
	ID int `json:"id"`
	// RepositoryName Repository name
	RepositoryName string   `json:"repositoryName"`
	Tags           []string `json:"tags,omitempty"`
}

func (repositoryTagsDeleteInput) MinimumParams() map[string]int {
	return map[string]int{
		"id": 1,
	}
}
