package main

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

// renderFile assembles one domain's generated source: the standard
// generated-code header (which is what internal/portainer/gen and
// internal/apiversion/applicability_gen.go both already carry, and what
// .golangci.yml's "generated: strict" exclusion keys off), the package
// clause, and every struct in structs in order — then formats the whole
// thing through go/format so the output is gofmt-clean by construction
// rather than by a separate `gofmt -w` step that could be skipped.
func renderFile(packageName, specPath string, structs []structSpec) ([]byte, error) {
	var buf strings.Builder
	buf.WriteString("// Code generated by cmd/gen_action_inputs from " + specPath + ". DO NOT EDIT.\n\n")
	buf.WriteString("package " + packageName + "\n\n")
	for i, s := range structs {
		if i > 0 {
			buf.WriteString("\n")
		}
		renderStruct(&buf, s)
	}
	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source for package %s: %w", packageName, err)
	}
	return formatted, nil
}

// duplicateStructName returns the first struct name that appears more than
// once in structs, and whether one was found.
//
// Nested struct names are bare concatenation of their parent's name and the
// property's Go field name (see typeOf), with nothing that detects two
// different properties concatenating to the same name — a body with a
// property "foo" (an object with its own object property "bar") and a
// sibling property "fooBar" (also an object) both produce a struct named
// "...FooBar". go/format only parses and re-indents; it has no notion of
// package-level redeclaration, so it formats such a file successfully and
// this generator would exit 0 having written source that does not compile.
// No such collision exists in the vendored spec today, which is exactly why
// this must be checked rather than left to be noticed: it is latent until
// whichever future spec bump introduces one.
func duplicateStructName(structs []structSpec) (string, bool) {
	seen := make(map[string]bool, len(structs))
	for _, s := range structs {
		if seen[s.Name] {
			return s.Name, true
		}
		seen[s.Name] = true
	}
	return "", false
}

func renderStruct(buf *strings.Builder, s structSpec) {
	if s.Doc != "" {
		writeComment(buf, s.Doc)
	}
	fmt.Fprintf(buf, "type %s struct {\n", s.Name)
	for _, f := range s.Fields {
		if f.Description != "" {
			writeIndentedComment(buf, f.GoName+" "+f.Description)
		}
		fmt.Fprintf(buf, "%s %s %s\n", f.GoName, f.GoType, jsonTag(f.JSONName, f.Required))
	}
	buf.WriteString("}\n")

	renderEnumParams(buf, s)
	renderMinimumParams(buf, s)
}

// renderEnumParams emits an EnumParams() method for s if any of its fields
// carry an enum constraint, implementing toolutil.EnumParams by structural
// typing — no import of internal/toolutil is needed for a generated domain
// package to satisfy an interface it already depends on transitively through
// toolutil.ActionSpec.
func renderEnumParams(buf *strings.Builder, s structSpec) {
	var withEnum []fieldSpec
	for _, f := range s.Fields {
		if len(f.Enum) > 0 {
			withEnum = append(withEnum, f)
		}
	}
	if len(withEnum) == 0 {
		return
	}
	fmt.Fprintf(buf, "\nfunc (%s) EnumParams() map[string][]any {\n", s.Name)
	buf.WriteString("\treturn map[string][]any{\n")
	for _, f := range withEnum {
		fmt.Fprintf(buf, "%q: {", f.JSONName)
		for i, v := range f.Enum {
			if i > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(renderEnumLiteral(v, f.EnumScalarType))
		}
		buf.WriteString("},\n")
	}
	buf.WriteString("\t}\n}\n")
}

// renderMinimumParams emits a MinimumParams() method for s if any of its
// fields carry a Minimum constraint (see fieldSpec.Minimum and
// isIdentifierPathParam), implementing toolutil.MinimumParams by structural
// typing — the same mechanism renderEnumParams already uses for EnumParams,
// for the same reason: no import of internal/toolutil is needed for a
// generated domain package to satisfy an interface it already depends on
// transitively through toolutil.ActionSpec.
func renderMinimumParams(buf *strings.Builder, s structSpec) {
	var withMin []fieldSpec
	for _, f := range s.Fields {
		if f.Minimum != nil {
			withMin = append(withMin, f)
		}
	}
	if len(withMin) == 0 {
		return
	}
	fmt.Fprintf(buf, "\nfunc (%s) MinimumParams() map[string]int {\n", s.Name)
	buf.WriteString("\treturn map[string]int{\n")
	for _, f := range withMin {
		fmt.Fprintf(buf, "%q: %d,\n", f.JSONName, *f.Minimum)
	}
	buf.WriteString("\t}\n}\n")
}

// renderEnumLiteral renders one enum value as a Go literal. Values arrive as
// decoded from the vendored spec's JSON via encoding/json into `any`, so a
// JSON number is always float64 regardless of the schema's declared
// "integer"/"number" type — scalarType is what tells this function which Go
// literal form the field's own type expects.
func renderEnumLiteral(v any, scalarType string) string {
	switch scalarType {
	case "integer":
		if f, ok := v.(float64); ok {
			return strconv.FormatInt(int64(f), 10)
		}
	case "number":
		if f, ok := v.(float64); ok {
			return strconv.FormatFloat(f, 'g', -1, 64)
		}
	case "boolean":
		if b, ok := v.(bool); ok {
			return strconv.FormatBool(b)
		}
	case "string":
		if s, ok := v.(string); ok {
			return fmt.Sprintf("%q", s)
		}
	}
	return fmt.Sprintf("%q", fmt.Sprint(v))
}

// writeComment renders text as a package-level doc comment.
func writeComment(buf *strings.Builder, text string) {
	for _, line := range strings.Split(text, "\n") {
		buf.WriteString("// " + line + "\n")
	}
}

// writeIndentedComment renders text as a field-level doc comment, indented to
// sit directly above the struct field it documents.
func writeIndentedComment(buf *strings.Builder, text string) {
	for _, line := range strings.Split(text, "\n") {
		buf.WriteString("\t// " + line + "\n")
	}
}
